package com.verificer.account.provider.mapper;

import com.verificer.account.provider.entity.AccountLog;
import com.verificer.beans.account.AccountLogQueryVo;

import java.util.List;

public interface AccountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_log
     *
     * @mbg.generated
     */
    int insert(AccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_log
     *
     * @mbg.generated
     */
    int insertSelective(AccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_log
     *
     * @mbg.generated
     */
    AccountLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccountLog record);

    List<AccountLog> page(AccountLogQueryVo accountLogQueryVo);

    List<AccountLog> pageAsc(AccountLogQueryVo accountLogQueryVo);


    int count(AccountLogQueryVo accountLogQueryVo);

}
