package com.verificer.account.provider.mapper;

import com.verificer.account.provider.entity.Account;
import com.verificer.beans.account.AccountVo;
import org.springframework.data.repository.query.Param;

import javax.annotation.PostConstruct;
import java.math.BigDecimal;
import java.util.List;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    Account selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Account record);

    Account selectByCustomerIdAndSubName(@Param("customerId") String customerId,@Param("subName") String subName);

    List<Account> selectByCustomerId(@Param("customerId") String customerId);

    Account selectByPrimaryKeyForUpdate(@Param("id") Long id);

    void updateBalByCustomerId(@Param("customerId") String customerId,@Param("amount") BigDecimal amount);

    List<AccountVo> selectByIdsForUpdate( List<Long> idList);
}
