package com.verificer.account.provider.mapper;

import com.verificer.account.provider.entity.SysAccountLog;

public interface SysAccountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_log
     *
     * @mbg.generated
     */
    int insert(SysAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_log
     *
     * @mbg.generated
     */
    int insertSelective(SysAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_log
     *
     * @mbg.generated
     */
    SysAccountLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysAccountLog record);
}
