package com.verificer.base_user.entity;

public class CustomerLoginRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_login_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_login_record.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_login_record.login_address
     *
     * @mbg.generated
     */
    private String loginAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_login_record.login_ip
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_login_record.login_time
     *
     * @mbg.generated
     */
    private Long loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_login_record.id
     *
     * @return the value of customer_login_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_login_record.id
     *
     * @param id the value for customer_login_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_login_record.customer_id
     *
     * @return the value of customer_login_record.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_login_record.customer_id
     *
     * @param customerId the value for customer_login_record.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_login_record.login_address
     *
     * @return the value of customer_login_record.login_address
     *
     * @mbg.generated
     */
    public String getLoginAddress() {
        return loginAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_login_record.login_address
     *
     * @param loginAddress the value for customer_login_record.login_address
     *
     * @mbg.generated
     */
    public void setLoginAddress(String loginAddress) {
        this.loginAddress = loginAddress == null ? null : loginAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_login_record.login_ip
     *
     * @return the value of customer_login_record.login_ip
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_login_record.login_ip
     *
     * @param loginIp the value for customer_login_record.login_ip
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_login_record.login_time
     *
     * @return the value of customer_login_record.login_time
     *
     * @mbg.generated
     */
    public Long getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_login_record.login_time
     *
     * @param loginTime the value for customer_login_record.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }
}