package com.verificer.base_user.entity;

public class CustomerVerified {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.national_id
     *
     * @mbg.generated
     */
    private Long nationalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.id_card_type
     *
     * @mbg.generated
     */
    private Integer idCardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.id_card_num
     *
     * @mbg.generated
     */
    private String idCardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.id_card_front_photo
     *
     * @mbg.generated
     */
    private String idCardFrontPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.id_card_back_photo
     *
     * @mbg.generated
     */
    private String idCardBackPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.id_card_real_photo
     *
     * @mbg.generated
     */
    private String idCardRealPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.reject_reason_code
     *
     * @mbg.generated
     */
    private String rejectReasonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.reject_reason_msg
     *
     * @mbg.generated
     */
    private String rejectReasonMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.review_time
     *
     * @mbg.generated
     */
    private Long reviewTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.jumio_remark
     *
     * @mbg.generated
     */
    private String jumioRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.jumio_biz_id
     *
     * @mbg.generated
     */
    private String jumioBizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.jumio_submit_time
     *
     * @mbg.generated
     */
    private Long jumioSubmitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.id_card_expire_time
     *
     * @mbg.generated
     */
    private Long idCardExpireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.jumio_birthday
     *
     * @mbg.generated
     */
    private String jumioBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.jumio_first_name
     *
     * @mbg.generated
     */
    private String jumioFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_verified.jumio_last_name
     *
     * @mbg.generated
     */
    private String jumioLastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.id
     *
     * @return the value of customer_verified.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.id
     *
     * @param id the value for customer_verified.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.customer_id
     *
     * @return the value of customer_verified.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.customer_id
     *
     * @param customerId the value for customer_verified.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.national_id
     *
     * @return the value of customer_verified.national_id
     *
     * @mbg.generated
     */
    public Long getNationalId() {
        return nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.national_id
     *
     * @param nationalId the value for customer_verified.national_id
     *
     * @mbg.generated
     */
    public void setNationalId(Long nationalId) {
        this.nationalId = nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.first_name
     *
     * @return the value of customer_verified.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.first_name
     *
     * @param firstName the value for customer_verified.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.last_name
     *
     * @return the value of customer_verified.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.last_name
     *
     * @param lastName the value for customer_verified.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.id_card_type
     *
     * @return the value of customer_verified.id_card_type
     *
     * @mbg.generated
     */
    public Integer getIdCardType() {
        return idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.id_card_type
     *
     * @param idCardType the value for customer_verified.id_card_type
     *
     * @mbg.generated
     */
    public void setIdCardType(Integer idCardType) {
        this.idCardType = idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.id_card_num
     *
     * @return the value of customer_verified.id_card_num
     *
     * @mbg.generated
     */
    public String getIdCardNum() {
        return idCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.id_card_num
     *
     * @param idCardNum the value for customer_verified.id_card_num
     *
     * @mbg.generated
     */
    public void setIdCardNum(String idCardNum) {
        this.idCardNum = idCardNum == null ? null : idCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.id_card_front_photo
     *
     * @return the value of customer_verified.id_card_front_photo
     *
     * @mbg.generated
     */
    public String getIdCardFrontPhoto() {
        return idCardFrontPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.id_card_front_photo
     *
     * @param idCardFrontPhoto the value for customer_verified.id_card_front_photo
     *
     * @mbg.generated
     */
    public void setIdCardFrontPhoto(String idCardFrontPhoto) {
        this.idCardFrontPhoto = idCardFrontPhoto == null ? null : idCardFrontPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.id_card_back_photo
     *
     * @return the value of customer_verified.id_card_back_photo
     *
     * @mbg.generated
     */
    public String getIdCardBackPhoto() {
        return idCardBackPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.id_card_back_photo
     *
     * @param idCardBackPhoto the value for customer_verified.id_card_back_photo
     *
     * @mbg.generated
     */
    public void setIdCardBackPhoto(String idCardBackPhoto) {
        this.idCardBackPhoto = idCardBackPhoto == null ? null : idCardBackPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.id_card_real_photo
     *
     * @return the value of customer_verified.id_card_real_photo
     *
     * @mbg.generated
     */
    public String getIdCardRealPhoto() {
        return idCardRealPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.id_card_real_photo
     *
     * @param idCardRealPhoto the value for customer_verified.id_card_real_photo
     *
     * @mbg.generated
     */
    public void setIdCardRealPhoto(String idCardRealPhoto) {
        this.idCardRealPhoto = idCardRealPhoto == null ? null : idCardRealPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.status
     *
     * @return the value of customer_verified.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.status
     *
     * @param status the value for customer_verified.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.reject_reason_code
     *
     * @return the value of customer_verified.reject_reason_code
     *
     * @mbg.generated
     */
    public String getRejectReasonCode() {
        return rejectReasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.reject_reason_code
     *
     * @param rejectReasonCode the value for customer_verified.reject_reason_code
     *
     * @mbg.generated
     */
    public void setRejectReasonCode(String rejectReasonCode) {
        this.rejectReasonCode = rejectReasonCode == null ? null : rejectReasonCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.reject_reason_msg
     *
     * @return the value of customer_verified.reject_reason_msg
     *
     * @mbg.generated
     */
    public String getRejectReasonMsg() {
        return rejectReasonMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.reject_reason_msg
     *
     * @param rejectReasonMsg the value for customer_verified.reject_reason_msg
     *
     * @mbg.generated
     */
    public void setRejectReasonMsg(String rejectReasonMsg) {
        this.rejectReasonMsg = rejectReasonMsg == null ? null : rejectReasonMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.create_time
     *
     * @return the value of customer_verified.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.create_time
     *
     * @param createTime the value for customer_verified.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.review_time
     *
     * @return the value of customer_verified.review_time
     *
     * @mbg.generated
     */
    public Long getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.review_time
     *
     * @param reviewTime the value for customer_verified.review_time
     *
     * @mbg.generated
     */
    public void setReviewTime(Long reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.jumio_remark
     *
     * @return the value of customer_verified.jumio_remark
     *
     * @mbg.generated
     */
    public String getJumioRemark() {
        return jumioRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.jumio_remark
     *
     * @param jumioRemark the value for customer_verified.jumio_remark
     *
     * @mbg.generated
     */
    public void setJumioRemark(String jumioRemark) {
        this.jumioRemark = jumioRemark == null ? null : jumioRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.jumio_biz_id
     *
     * @return the value of customer_verified.jumio_biz_id
     *
     * @mbg.generated
     */
    public String getJumioBizId() {
        return jumioBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.jumio_biz_id
     *
     * @param jumioBizId the value for customer_verified.jumio_biz_id
     *
     * @mbg.generated
     */
    public void setJumioBizId(String jumioBizId) {
        this.jumioBizId = jumioBizId == null ? null : jumioBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.jumio_submit_time
     *
     * @return the value of customer_verified.jumio_submit_time
     *
     * @mbg.generated
     */
    public Long getJumioSubmitTime() {
        return jumioSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.jumio_submit_time
     *
     * @param jumioSubmitTime the value for customer_verified.jumio_submit_time
     *
     * @mbg.generated
     */
    public void setJumioSubmitTime(Long jumioSubmitTime) {
        this.jumioSubmitTime = jumioSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.id_card_expire_time
     *
     * @return the value of customer_verified.id_card_expire_time
     *
     * @mbg.generated
     */
    public Long getIdCardExpireTime() {
        return idCardExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.id_card_expire_time
     *
     * @param idCardExpireTime the value for customer_verified.id_card_expire_time
     *
     * @mbg.generated
     */
    public void setIdCardExpireTime(Long idCardExpireTime) {
        this.idCardExpireTime = idCardExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.birthday
     *
     * @return the value of customer_verified.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.birthday
     *
     * @param birthday the value for customer_verified.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.jumio_birthday
     *
     * @return the value of customer_verified.jumio_birthday
     *
     * @mbg.generated
     */
    public String getJumioBirthday() {
        return jumioBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.jumio_birthday
     *
     * @param jumioBirthday the value for customer_verified.jumio_birthday
     *
     * @mbg.generated
     */
    public void setJumioBirthday(String jumioBirthday) {
        this.jumioBirthday = jumioBirthday == null ? null : jumioBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.jumio_first_name
     *
     * @return the value of customer_verified.jumio_first_name
     *
     * @mbg.generated
     */
    public String getJumioFirstName() {
        return jumioFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.jumio_first_name
     *
     * @param jumioFirstName the value for customer_verified.jumio_first_name
     *
     * @mbg.generated
     */
    public void setJumioFirstName(String jumioFirstName) {
        this.jumioFirstName = jumioFirstName == null ? null : jumioFirstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_verified.jumio_last_name
     *
     * @return the value of customer_verified.jumio_last_name
     *
     * @mbg.generated
     */
    public String getJumioLastName() {
        return jumioLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_verified.jumio_last_name
     *
     * @param jumioLastName the value for customer_verified.jumio_last_name
     *
     * @mbg.generated
     */
    public void setJumioLastName(String jumioLastName) {
        this.jumioLastName = jumioLastName == null ? null : jumioLastName.trim();
    }
}
