package com.verificer.base_user.entity;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.channel_id
     *
     * @mbg.generated
     */
    private String channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.enable
     *
     * @mbg.generated
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.google_secret
     *
     * @mbg.generated
     */
    private String googleSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.google_secret_auth
     *
     * @mbg.generated
     */
    private Boolean googleSecretAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.has_pay_password
     *
     * @mbg.generated
     */
    private Boolean hasPayPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id_card_no
     *
     * @mbg.generated
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id_info_status
     *
     * @mbg.generated
     */
    private Integer idInfoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.inviter
     *
     * @mbg.generated
     */
    private Long inviter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.invite_code
     *
     * @mbg.generated
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_login_ip
     *
     * @mbg.generated
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_login_time
     *
     * @mbg.generated
     */
    private Long lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mail_auth
     *
     * @mbg.generated
     */
    private Boolean mailAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mobile_auth
     *
     * @mbg.generated
     */
    private Boolean mobileAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.national_id
     *
     * @mbg.generated
     */
    private Long nationalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.pay_password
     *
     * @mbg.generated
     */
    private String payPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.reg_time
     *
     * @mbg.generated
     */
    private Long regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.reg_type
     *
     * @mbg.generated
     */
    private Integer regType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.login_token
     *
     * @mbg.generated
     */
    private String loginToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.invite_link
     *
     * @mbg.generated
     */
    private String inviteLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.relation
     *
     * @mbg.generated
     */
    private String relation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.google_auth_is_open
     *
     * @mbg.generated
     */
    private Boolean googleAuthIsOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.withdraw_google_auth_is_open
     *
     * @mbg.generated
     */
    private Boolean withdrawGoogleAuthIsOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_insider
     *
     * @mbg.generated
     */
    private Boolean isInsider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_allow_robot_api
     *
     * @mbg.generated
     */
    private Boolean isAllowRobotApi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_qmgt_exchange_account
     *
     * @mbg.generated
     */
    private Boolean isQmgtExchangeAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.has_recharge
     *
     * @mbg.generated
     */
    private Boolean hasRecharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.links
     *
     * @mbg.generated
     */
    private String links;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.wallet_address
     *
     * @mbg.generated
     */
    private String walletAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Is_activation
     *
     * @mbg.generated
     */
    private Boolean isActivation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.username
     *
     * @return the value of customer.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.username
     *
     * @param username the value for customer.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.channel_id
     *
     * @return the value of customer.channel_id
     *
     * @mbg.generated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.channel_id
     *
     * @param channelId the value for customer.channel_id
     *
     * @mbg.generated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.create_time
     *
     * @return the value of customer.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.create_time
     *
     * @param createTime the value for customer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.enable
     *
     * @return the value of customer.enable
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.enable
     *
     * @param enable the value for customer.enable
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.google_secret
     *
     * @return the value of customer.google_secret
     *
     * @mbg.generated
     */
    public String getGoogleSecret() {
        return googleSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.google_secret
     *
     * @param googleSecret the value for customer.google_secret
     *
     * @mbg.generated
     */
    public void setGoogleSecret(String googleSecret) {
        this.googleSecret = googleSecret == null ? null : googleSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.google_secret_auth
     *
     * @return the value of customer.google_secret_auth
     *
     * @mbg.generated
     */
    public Boolean getGoogleSecretAuth() {
        return googleSecretAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.google_secret_auth
     *
     * @param googleSecretAuth the value for customer.google_secret_auth
     *
     * @mbg.generated
     */
    public void setGoogleSecretAuth(Boolean googleSecretAuth) {
        this.googleSecretAuth = googleSecretAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.has_pay_password
     *
     * @return the value of customer.has_pay_password
     *
     * @mbg.generated
     */
    public Boolean getHasPayPassword() {
        return hasPayPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.has_pay_password
     *
     * @param hasPayPassword the value for customer.has_pay_password
     *
     * @mbg.generated
     */
    public void setHasPayPassword(Boolean hasPayPassword) {
        this.hasPayPassword = hasPayPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id_card_no
     *
     * @return the value of customer.id_card_no
     *
     * @mbg.generated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id_card_no
     *
     * @param idCardNo the value for customer.id_card_no
     *
     * @mbg.generated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id_info_status
     *
     * @return the value of customer.id_info_status
     *
     * @mbg.generated
     */
    public Integer getIdInfoStatus() {
        return idInfoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id_info_status
     *
     * @param idInfoStatus the value for customer.id_info_status
     *
     * @mbg.generated
     */
    public void setIdInfoStatus(Integer idInfoStatus) {
        this.idInfoStatus = idInfoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.inviter
     *
     * @return the value of customer.inviter
     *
     * @mbg.generated
     */
    public Long getInviter() {
        return inviter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.inviter
     *
     * @param inviter the value for customer.inviter
     *
     * @mbg.generated
     */
    public void setInviter(Long inviter) {
        this.inviter = inviter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.invite_code
     *
     * @return the value of customer.invite_code
     *
     * @mbg.generated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.invite_code
     *
     * @param inviteCode the value for customer.invite_code
     *
     * @mbg.generated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_login_ip
     *
     * @return the value of customer.last_login_ip
     *
     * @mbg.generated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_login_ip
     *
     * @param lastLoginIp the value for customer.last_login_ip
     *
     * @mbg.generated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_login_time
     *
     * @return the value of customer.last_login_time
     *
     * @mbg.generated
     */
    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_login_time
     *
     * @param lastLoginTime the value for customer.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mail_auth
     *
     * @return the value of customer.mail_auth
     *
     * @mbg.generated
     */
    public Boolean getMailAuth() {
        return mailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mail_auth
     *
     * @param mailAuth the value for customer.mail_auth
     *
     * @mbg.generated
     */
    public void setMailAuth(Boolean mailAuth) {
        this.mailAuth = mailAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mobile
     *
     * @return the value of customer.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mobile
     *
     * @param mobile the value for customer.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mobile_auth
     *
     * @return the value of customer.mobile_auth
     *
     * @mbg.generated
     */
    public Boolean getMobileAuth() {
        return mobileAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mobile_auth
     *
     * @param mobileAuth the value for customer.mobile_auth
     *
     * @mbg.generated
     */
    public void setMobileAuth(Boolean mobileAuth) {
        this.mobileAuth = mobileAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.national_id
     *
     * @return the value of customer.national_id
     *
     * @mbg.generated
     */
    public Long getNationalId() {
        return nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.national_id
     *
     * @param nationalId the value for customer.national_id
     *
     * @mbg.generated
     */
    public void setNationalId(Long nationalId) {
        this.nationalId = nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.password
     *
     * @return the value of customer.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.password
     *
     * @param password the value for customer.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.pay_password
     *
     * @return the value of customer.pay_password
     *
     * @mbg.generated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.pay_password
     *
     * @param payPassword the value for customer.pay_password
     *
     * @mbg.generated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.first_name
     *
     * @return the value of customer.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.first_name
     *
     * @param firstName the value for customer.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_name
     *
     * @return the value of customer.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_name
     *
     * @param lastName the value for customer.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.real_name
     *
     * @return the value of customer.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.real_name
     *
     * @param realName the value for customer.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.reg_time
     *
     * @return the value of customer.reg_time
     *
     * @mbg.generated
     */
    public Long getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.reg_time
     *
     * @param regTime the value for customer.reg_time
     *
     * @mbg.generated
     */
    public void setRegTime(Long regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.reg_type
     *
     * @return the value of customer.reg_type
     *
     * @mbg.generated
     */
    public Integer getRegType() {
        return regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.reg_type
     *
     * @param regType the value for customer.reg_type
     *
     * @mbg.generated
     */
    public void setRegType(Integer regType) {
        this.regType = regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.update_time
     *
     * @return the value of customer.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.update_time
     *
     * @param updateTime the value for customer.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.login_token
     *
     * @return the value of customer.login_token
     *
     * @mbg.generated
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.login_token
     *
     * @param loginToken the value for customer.login_token
     *
     * @mbg.generated
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken == null ? null : loginToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.invite_link
     *
     * @return the value of customer.invite_link
     *
     * @mbg.generated
     */
    public String getInviteLink() {
        return inviteLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.invite_link
     *
     * @param inviteLink the value for customer.invite_link
     *
     * @mbg.generated
     */
    public void setInviteLink(String inviteLink) {
        this.inviteLink = inviteLink == null ? null : inviteLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.relation
     *
     * @return the value of customer.relation
     *
     * @mbg.generated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.relation
     *
     * @param relation the value for customer.relation
     *
     * @mbg.generated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.google_auth_is_open
     *
     * @return the value of customer.google_auth_is_open
     *
     * @mbg.generated
     */
    public Boolean getGoogleAuthIsOpen() {
        return googleAuthIsOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.google_auth_is_open
     *
     * @param googleAuthIsOpen the value for customer.google_auth_is_open
     *
     * @mbg.generated
     */
    public void setGoogleAuthIsOpen(Boolean googleAuthIsOpen) {
        this.googleAuthIsOpen = googleAuthIsOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.withdraw_google_auth_is_open
     *
     * @return the value of customer.withdraw_google_auth_is_open
     *
     * @mbg.generated
     */
    public Boolean getWithdrawGoogleAuthIsOpen() {
        return withdrawGoogleAuthIsOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.withdraw_google_auth_is_open
     *
     * @param withdrawGoogleAuthIsOpen the value for customer.withdraw_google_auth_is_open
     *
     * @mbg.generated
     */
    public void setWithdrawGoogleAuthIsOpen(Boolean withdrawGoogleAuthIsOpen) {
        this.withdrawGoogleAuthIsOpen = withdrawGoogleAuthIsOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_insider
     *
     * @return the value of customer.is_insider
     *
     * @mbg.generated
     */
    public Boolean getIsInsider() {
        return isInsider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_insider
     *
     * @param isInsider the value for customer.is_insider
     *
     * @mbg.generated
     */
    public void setIsInsider(Boolean isInsider) {
        this.isInsider = isInsider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_allow_robot_api
     *
     * @return the value of customer.is_allow_robot_api
     *
     * @mbg.generated
     */
    public Boolean getIsAllowRobotApi() {
        return isAllowRobotApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_allow_robot_api
     *
     * @param isAllowRobotApi the value for customer.is_allow_robot_api
     *
     * @mbg.generated
     */
    public void setIsAllowRobotApi(Boolean isAllowRobotApi) {
        this.isAllowRobotApi = isAllowRobotApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_qmgt_exchange_account
     *
     * @return the value of customer.is_qmgt_exchange_account
     *
     * @mbg.generated
     */
    public Boolean getIsQmgtExchangeAccount() {
        return isQmgtExchangeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_qmgt_exchange_account
     *
     * @param isQmgtExchangeAccount the value for customer.is_qmgt_exchange_account
     *
     * @mbg.generated
     */
    public void setIsQmgtExchangeAccount(Boolean isQmgtExchangeAccount) {
        this.isQmgtExchangeAccount = isQmgtExchangeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.has_recharge
     *
     * @return the value of customer.has_recharge
     *
     * @mbg.generated
     */
    public Boolean getHasRecharge() {
        return hasRecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.has_recharge
     *
     * @param hasRecharge the value for customer.has_recharge
     *
     * @mbg.generated
     */
    public void setHasRecharge(Boolean hasRecharge) {
        this.hasRecharge = hasRecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.avatar
     *
     * @return the value of customer.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.avatar
     *
     * @param avatar the value for customer.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.nick_name
     *
     * @return the value of customer.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.nick_name
     *
     * @param nickName the value for customer.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.remark
     *
     * @return the value of customer.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.remark
     *
     * @param remark the value for customer.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.links
     *
     * @return the value of customer.links
     *
     * @mbg.generated
     */
    public String getLinks() {
        return links;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.links
     *
     * @param links the value for customer.links
     *
     * @mbg.generated
     */
    public void setLinks(String links) {
        this.links = links == null ? null : links.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.wallet_address
     *
     * @return the value of customer.wallet_address
     *
     * @mbg.generated
     */
    public String getWalletAddress() {
        return walletAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.wallet_address
     *
     * @param walletAddress the value for customer.wallet_address
     *
     * @mbg.generated
     */
    public void setWalletAddress(String walletAddress) {
        this.walletAddress = walletAddress == null ? null : walletAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Is_activation
     *
     * @return the value of customer.Is_activation
     *
     * @mbg.generated
     */
    public Boolean getIsActivation() {
        return isActivation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Is_activation
     *
     * @param isActivation the value for customer.Is_activation
     *
     * @mbg.generated
     */
    public void setIsActivation(Boolean isActivation) {
        this.isActivation = isActivation;
    }
}
