package com.verificer.base_user.entity;

public class JumioTransaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.out_customer_id
     *
     * @mbg.generated
     */
    private String outCustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.inner_transaction_id
     *
     * @mbg.generated
     */
    private String innerTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.jumio_transaction_id
     *
     * @mbg.generated
     */
    private String jumioTransactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.national_id
     *
     * @mbg.generated
     */
    private Long nationalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.has_process_time_out
     *
     * @mbg.generated
     */
    private Boolean hasProcessTimeOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.has_submitted_to_jumio
     *
     * @mbg.generated
     */
    private Boolean hasSubmittedToJumio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.has_callback
     *
     * @mbg.generated
     */
    private Boolean hasCallback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jumio_transaction.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.id
     *
     * @return the value of jumio_transaction.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.id
     *
     * @param id the value for jumio_transaction.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.customer_id
     *
     * @return the value of jumio_transaction.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.customer_id
     *
     * @param customerId the value for jumio_transaction.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.out_customer_id
     *
     * @return the value of jumio_transaction.out_customer_id
     *
     * @mbg.generated
     */
    public String getOutCustomerId() {
        return outCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.out_customer_id
     *
     * @param outCustomerId the value for jumio_transaction.out_customer_id
     *
     * @mbg.generated
     */
    public void setOutCustomerId(String outCustomerId) {
        this.outCustomerId = outCustomerId == null ? null : outCustomerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.inner_transaction_id
     *
     * @return the value of jumio_transaction.inner_transaction_id
     *
     * @mbg.generated
     */
    public String getInnerTransactionId() {
        return innerTransactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.inner_transaction_id
     *
     * @param innerTransactionId the value for jumio_transaction.inner_transaction_id
     *
     * @mbg.generated
     */
    public void setInnerTransactionId(String innerTransactionId) {
        this.innerTransactionId = innerTransactionId == null ? null : innerTransactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.jumio_transaction_id
     *
     * @return the value of jumio_transaction.jumio_transaction_id
     *
     * @mbg.generated
     */
    public String getJumioTransactionId() {
        return jumioTransactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.jumio_transaction_id
     *
     * @param jumioTransactionId the value for jumio_transaction.jumio_transaction_id
     *
     * @mbg.generated
     */
    public void setJumioTransactionId(String jumioTransactionId) {
        this.jumioTransactionId = jumioTransactionId == null ? null : jumioTransactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.first_name
     *
     * @return the value of jumio_transaction.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.first_name
     *
     * @param firstName the value for jumio_transaction.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.last_name
     *
     * @return the value of jumio_transaction.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.last_name
     *
     * @param lastName the value for jumio_transaction.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.birthday
     *
     * @return the value of jumio_transaction.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.birthday
     *
     * @param birthday the value for jumio_transaction.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.national_id
     *
     * @return the value of jumio_transaction.national_id
     *
     * @mbg.generated
     */
    public Long getNationalId() {
        return nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.national_id
     *
     * @param nationalId the value for jumio_transaction.national_id
     *
     * @mbg.generated
     */
    public void setNationalId(Long nationalId) {
        this.nationalId = nationalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.has_process_time_out
     *
     * @return the value of jumio_transaction.has_process_time_out
     *
     * @mbg.generated
     */
    public Boolean getHasProcessTimeOut() {
        return hasProcessTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.has_process_time_out
     *
     * @param hasProcessTimeOut the value for jumio_transaction.has_process_time_out
     *
     * @mbg.generated
     */
    public void setHasProcessTimeOut(Boolean hasProcessTimeOut) {
        this.hasProcessTimeOut = hasProcessTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.has_submitted_to_jumio
     *
     * @return the value of jumio_transaction.has_submitted_to_jumio
     *
     * @mbg.generated
     */
    public Boolean getHasSubmittedToJumio() {
        return hasSubmittedToJumio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.has_submitted_to_jumio
     *
     * @param hasSubmittedToJumio the value for jumio_transaction.has_submitted_to_jumio
     *
     * @mbg.generated
     */
    public void setHasSubmittedToJumio(Boolean hasSubmittedToJumio) {
        this.hasSubmittedToJumio = hasSubmittedToJumio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.has_callback
     *
     * @return the value of jumio_transaction.has_callback
     *
     * @mbg.generated
     */
    public Boolean getHasCallback() {
        return hasCallback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.has_callback
     *
     * @param hasCallback the value for jumio_transaction.has_callback
     *
     * @mbg.generated
     */
    public void setHasCallback(Boolean hasCallback) {
        this.hasCallback = hasCallback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jumio_transaction.create_time
     *
     * @return the value of jumio_transaction.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jumio_transaction.create_time
     *
     * @param createTime the value for jumio_transaction.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
