package com.verificer.base_user.entity;

public class WhiteListApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.exchange_id
     *
     * @mbg.generated
     */
    private Integer exchangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.apply_staff_id
     *
     * @mbg.generated
     */
    private Long applyStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.apply_staff_name
     *
     * @mbg.generated
     */
    private String applyStaffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.audit_staff_id
     *
     * @mbg.generated
     */
    private Long auditStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.audit_staff_name
     *
     * @mbg.generated
     */
    private String auditStaffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.apply_status
     *
     * @mbg.generated
     */
    private Integer applyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.apply_type
     *
     * @mbg.generated
     */
    private Integer applyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list_apply.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.id
     *
     * @return the value of white_list_apply.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.id
     *
     * @param id the value for white_list_apply.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.customer_id
     *
     * @return the value of white_list_apply.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.customer_id
     *
     * @param customerId the value for white_list_apply.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.exchange_id
     *
     * @return the value of white_list_apply.exchange_id
     *
     * @mbg.generated
     */
    public Integer getExchangeId() {
        return exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.exchange_id
     *
     * @param exchangeId the value for white_list_apply.exchange_id
     *
     * @mbg.generated
     */
    public void setExchangeId(Integer exchangeId) {
        this.exchangeId = exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.note
     *
     * @return the value of white_list_apply.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.note
     *
     * @param note the value for white_list_apply.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.apply_staff_id
     *
     * @return the value of white_list_apply.apply_staff_id
     *
     * @mbg.generated
     */
    public Long getApplyStaffId() {
        return applyStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.apply_staff_id
     *
     * @param applyStaffId the value for white_list_apply.apply_staff_id
     *
     * @mbg.generated
     */
    public void setApplyStaffId(Long applyStaffId) {
        this.applyStaffId = applyStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.apply_staff_name
     *
     * @return the value of white_list_apply.apply_staff_name
     *
     * @mbg.generated
     */
    public String getApplyStaffName() {
        return applyStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.apply_staff_name
     *
     * @param applyStaffName the value for white_list_apply.apply_staff_name
     *
     * @mbg.generated
     */
    public void setApplyStaffName(String applyStaffName) {
        this.applyStaffName = applyStaffName == null ? null : applyStaffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.audit_staff_id
     *
     * @return the value of white_list_apply.audit_staff_id
     *
     * @mbg.generated
     */
    public Long getAuditStaffId() {
        return auditStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.audit_staff_id
     *
     * @param auditStaffId the value for white_list_apply.audit_staff_id
     *
     * @mbg.generated
     */
    public void setAuditStaffId(Long auditStaffId) {
        this.auditStaffId = auditStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.audit_staff_name
     *
     * @return the value of white_list_apply.audit_staff_name
     *
     * @mbg.generated
     */
    public String getAuditStaffName() {
        return auditStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.audit_staff_name
     *
     * @param auditStaffName the value for white_list_apply.audit_staff_name
     *
     * @mbg.generated
     */
    public void setAuditStaffName(String auditStaffName) {
        this.auditStaffName = auditStaffName == null ? null : auditStaffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.apply_status
     *
     * @return the value of white_list_apply.apply_status
     *
     * @mbg.generated
     */
    public Integer getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.apply_status
     *
     * @param applyStatus the value for white_list_apply.apply_status
     *
     * @mbg.generated
     */
    public void setApplyStatus(Integer applyStatus) {
        this.applyStatus = applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.apply_type
     *
     * @return the value of white_list_apply.apply_type
     *
     * @mbg.generated
     */
    public Integer getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.apply_type
     *
     * @param applyType the value for white_list_apply.apply_type
     *
     * @mbg.generated
     */
    public void setApplyType(Integer applyType) {
        this.applyType = applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.create_time
     *
     * @return the value of white_list_apply.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.create_time
     *
     * @param createTime the value for white_list_apply.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list_apply.update_time
     *
     * @return the value of white_list_apply.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list_apply.update_time
     *
     * @param updateTime the value for white_list_apply.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}