package com.verificer.base_user.mapper;

import com.verificer.base_user.entity.CustomerLoginRecord;

public interface CustomerLoginRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_record
     *
     * @mbg.generated
     */
    int insert(CustomerLoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_record
     *
     * @mbg.generated
     */
    int insertSelective(CustomerLoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_record
     *
     * @mbg.generated
     */
    CustomerLoginRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerLoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerLoginRecord record);
}