package com.verificer.base_user.mapper;

import com.verificer.base_user.entity.CustomerActivation;
import com.verificer.base_user.entity.CustomerAttach;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attach
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attach
     *
     * @mbg.generated
     */
    int insert(CustomerAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attach
     *
     * @mbg.generated
     */
    int insertSelective(CustomerAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attach
     *
     * @mbg.generated
     */
    CustomerAttach selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerAttach record);

    List<CustomerAttach> selectByCustomerId(@Param("customerId") Long customerId);

}