package com.verificer.base_user.mapper;

import com.verificer.base_user.entity.Customer;
import com.verificer.beans.CustomerListQueryVo;
import com.verificer.beans.customer.req.CustomerPageVo;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    Customer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Customer record);

    Customer selectByEmail(@Param("email") String email);

    Customer selectByMobile(@Param("mobile") String mobile);

    Customer selectByUsername(@Param("username") String username);

    Customer selectByInviteCode(@Param("inviteCode") String inviteCode);

    Customer selectByPrimaryKeyForUpdate(@Param("id") Long id);

    List<Customer> page(CustomerListQueryVo customerListQueryVo);

    int count(CustomerListQueryVo customerListQueryVo);

    List<Customer> selectByRoleId(@Param("roleId") Long roleId);

    List<Customer> selectByNickname(@Param("nickname") String nickname,
                                    @Param("limit") Integer limit);

    List<Customer> extendPage(CustomerPageVo queryVo);

    int extendCount(CustomerPageVo queryVo);

    Customer selectByWalletAddress(@Param("walletAddress") String walletAddress);

}