package com.verificer.base_user.mapper;

import com.verificer.base_user.entity.JumioTransaction;
import org.apache.ibatis.annotations.Param;

public interface JumioTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumio_transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumio_transaction
     *
     * @mbg.generated
     */
    int insert(JumioTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumio_transaction
     *
     * @mbg.generated
     */
    int insertSelective(JumioTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumio_transaction
     *
     * @mbg.generated
     */
    JumioTransaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumio_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JumioTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jumio_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JumioTransaction record);

    JumioTransaction selectLastByOutCustomerId(@Param("outCustomerId") String outCustomerId);


    JumioTransaction selectCallbackTimeoutTran(@Param("expireTime") Long expireTime);
}
