package com.verificer.base_user.mapper;

import com.verificer.base_user.entity.National;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NationalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table national
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table national
     *
     * @mbg.generated
     */
    int insert(National record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table national
     *
     * @mbg.generated
     */
    int insertSelective(National record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table national
     *
     * @mbg.generated
     */
    National selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table national
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(National record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table national
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(National record);

    List<National> queryEnableNational();

    National selectByNationCode(@Param("nationCode") String nationCode);
}