package com.verificer.base_user.mapper;

import com.verificer.base_user.entity.WhiteListApply;
import com.verificer.beans.WhiteListQueryVo;

import java.util.List;

public interface WhiteListApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list_apply
     *
     * @mbg.generated
     */
    int insert(WhiteListApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list_apply
     *
     * @mbg.generated
     */
    int insertSelective(WhiteListApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list_apply
     *
     * @mbg.generated
     */
    WhiteListApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WhiteListApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WhiteListApply record);

    List<WhiteListApply> page(WhiteListQueryVo whiteListQueryVo);

    int count(WhiteListQueryVo whiteListQureyVo);
}