package com.verificer.base.auth.mapper;

import com.verificer.base.auth.entity.RAuthMenu;

public interface RAuthMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_menu
     *
     * @mbg.generated
     */
    int insert(RAuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_menu
     *
     * @mbg.generated
     */
    int insertSelective(RAuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_menu
     *
     * @mbg.generated
     */
    RAuthMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RAuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RAuthMenu record);
}