package com.verificer.base.auth.mapper;

import com.verificer.base.auth.entity.RUserRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int insert(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int insertSelective(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    RUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RUserRole record);

    List<RUserRole> selectByUserId(@Param("userId") Long userId);

    void deleteByUserId(@Param("userId") Long userId);
}