package com.verificer.base.auth.entity;

public class RAuthMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_auth_menu.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_auth_menu.auth_code
     *
     * @mbg.generated
     */
    private String authCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_auth_menu.menu_code
     *
     * @mbg.generated
     */
    private String menuCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_auth_menu.id
     *
     * @return the value of r_auth_menu.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_auth_menu.id
     *
     * @param id the value for r_auth_menu.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_auth_menu.auth_code
     *
     * @return the value of r_auth_menu.auth_code
     *
     * @mbg.generated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_auth_menu.auth_code
     *
     * @param authCode the value for r_auth_menu.auth_code
     *
     * @mbg.generated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_auth_menu.menu_code
     *
     * @return the value of r_auth_menu.menu_code
     *
     * @mbg.generated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_auth_menu.menu_code
     *
     * @param menuCode the value for r_auth_menu.menu_code
     *
     * @mbg.generated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }
}