package com.verificer.base.auth.entity;

public class RRoleAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_role_auth.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_role_auth.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_role_auth.auth_code
     *
     * @mbg.generated
     */
    private String authCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_role_auth.id
     *
     * @return the value of r_role_auth.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_role_auth.id
     *
     * @param id the value for r_role_auth.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_role_auth.role_id
     *
     * @return the value of r_role_auth.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_role_auth.role_id
     *
     * @param roleId the value for r_role_auth.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_role_auth.auth_code
     *
     * @return the value of r_role_auth.auth_code
     *
     * @mbg.generated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_role_auth.auth_code
     *
     * @param authCode the value for r_role_auth.auth_code
     *
     * @mbg.generated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }
}