package com.verificer.base.sup.pvd.entity;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.image_uri
     *
     * @mbg.generated
     */
    private String imageUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.html_url
     *
     * @mbg.generated
     */
    private String htmlUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.html_title
     *
     * @mbg.generated
     */
    private String htmlTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.enable
     *
     * @mbg.generated
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.sort_parameter
     *
     * @mbg.generated
     */
    private Integer sortParameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.international_type
     *
     * @mbg.generated
     */
    private String internationalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.terminal_type
     *
     * @mbg.generated
     */
    private Integer terminalType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.id
     *
     * @param id the value for banner.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.name
     *
     * @return the value of banner.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.name
     *
     * @param name the value for banner.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.content
     *
     * @return the value of banner.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.content
     *
     * @param content the value for banner.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.image_uri
     *
     * @return the value of banner.image_uri
     *
     * @mbg.generated
     */
    public String getImageUri() {
        return imageUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.image_uri
     *
     * @param imageUri the value for banner.image_uri
     *
     * @mbg.generated
     */
    public void setImageUri(String imageUri) {
        this.imageUri = imageUri == null ? null : imageUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.html_url
     *
     * @return the value of banner.html_url
     *
     * @mbg.generated
     */
    public String getHtmlUrl() {
        return htmlUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.html_url
     *
     * @param htmlUrl the value for banner.html_url
     *
     * @mbg.generated
     */
    public void setHtmlUrl(String htmlUrl) {
        this.htmlUrl = htmlUrl == null ? null : htmlUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.html_title
     *
     * @return the value of banner.html_title
     *
     * @mbg.generated
     */
    public String getHtmlTitle() {
        return htmlTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.html_title
     *
     * @param htmlTitle the value for banner.html_title
     *
     * @mbg.generated
     */
    public void setHtmlTitle(String htmlTitle) {
        this.htmlTitle = htmlTitle == null ? null : htmlTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.enable
     *
     * @return the value of banner.enable
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.enable
     *
     * @param enable the value for banner.enable
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.create_time
     *
     * @return the value of banner.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.create_time
     *
     * @param createTime the value for banner.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.end_time
     *
     * @return the value of banner.end_time
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.end_time
     *
     * @param endTime the value for banner.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.update_time
     *
     * @return the value of banner.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.update_time
     *
     * @param updateTime the value for banner.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.sort_parameter
     *
     * @return the value of banner.sort_parameter
     *
     * @mbg.generated
     */
    public Integer getSortParameter() {
        return sortParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.sort_parameter
     *
     * @param sortParameter the value for banner.sort_parameter
     *
     * @mbg.generated
     */
    public void setSortParameter(Integer sortParameter) {
        this.sortParameter = sortParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.international_type
     *
     * @return the value of banner.international_type
     *
     * @mbg.generated
     */
    public String getInternationalType() {
        return internationalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.international_type
     *
     * @param internationalType the value for banner.international_type
     *
     * @mbg.generated
     */
    public void setInternationalType(String internationalType) {
        this.internationalType = internationalType == null ? null : internationalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.terminal_type
     *
     * @return the value of banner.terminal_type
     *
     * @mbg.generated
     */
    public Integer getTerminalType() {
        return terminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.terminal_type
     *
     * @param terminalType the value for banner.terminal_type
     *
     * @mbg.generated
     */
    public void setTerminalType(Integer terminalType) {
        this.terminalType = terminalType;
    }
}
