package com.verificer.base.sup.pvd.mapper;

import com.verificer.base.sup.pvd.entity.Help;
import com.verificer.beans.HelpPageVo;

import java.util.List;

public interface HelpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help
     *
     * @mbg.generated
     */
    int insert(Help record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help
     *
     * @mbg.generated
     */
    int insertSelective(Help record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help
     *
     * @mbg.generated
     */
    Help selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Help record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Help record);

    List<Help> page(HelpPageVo queryVo);

    int count(HelpPageVo queryVo);
}
