package com.verificer.biz.biz.mapper;

import com.verificer.biz.biz.entity.Addr;

public interface AddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addr
     *
     * @mbg.generated
     */
    int insert(Addr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addr
     *
     * @mbg.generated
     */
    int insertSelective(Addr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addr
     *
     * @mbg.generated
     */
    Addr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Addr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Addr record);
}
