package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.AdjustVo;
import com.verificer.biz.beans.vo.req.AdjustPageVo;
import com.verificer.biz.biz.entity.Adjust;

import java.util.List;

public interface AdjustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust
     *
     * @mbg.generated
     */
    int insert(Adjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust
     *
     * @mbg.generated
     */
    int insertSelective(Adjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust
     *
     * @mbg.generated
     */
    Adjust selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Adjust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjust
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Adjust record);

    List<Adjust> page(AdjustPageVo qryVo);

    int count(AdjustPageVo qryVo);
}
