package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.req.OrderPageVo;
import com.verificer.biz.biz.entity.DbgOrder;

import java.util.List;

public interface DbgOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbg_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbg_order
     *
     * @mbg.generated
     */
    int insert(DbgOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbg_order
     *
     * @mbg.generated
     */
    int insertSelective(DbgOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbg_order
     *
     * @mbg.generated
     */
    DbgOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbg_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbgOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbg_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbgOrder record);

    List<DbgOrder> page(OrderPageVo qryVo);

    int count(OrderPageVo qryVo);
}
