package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.user.member.MemberStaBaseVo;
import com.verificer.biz.beans.vo.user.member.MemberStaQryVo;
import com.verificer.biz.biz.entity.MemberOrder;
import org.apache.ibatis.annotations.Param;

public interface MemberOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_order
     *
     * @mbg.generated
     */
    int insert(MemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_order
     *
     * @mbg.generated
     */
    int insertSelective(MemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_order
     *
     * @mbg.generated
     */
    MemberOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberOrder record);

    MemberOrder getAndLock(@Param("id") Long id);

    MemberOrder selectByUserIdAndStatusLimit1(@Param("userId") Long userId, @Param("status")Integer value);

    MemberStaBaseVo memberSta(MemberStaQryVo allQryVo);
}
