package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.user.withdraw.ReferrerWithdrawPageVo;
import com.verificer.biz.beans.vo.user.withdraw.ReferrerWithdrawVo;
import com.verificer.biz.biz.entity.ReferrerWithdraw;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReferrerWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_withdraw
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_withdraw
     *
     * @mbg.generated
     */
    int insert(ReferrerWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_withdraw
     *
     * @mbg.generated
     */
    int insertSelective(ReferrerWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_withdraw
     *
     * @mbg.generated
     */
    ReferrerWithdraw selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReferrerWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReferrerWithdraw record);

    ReferrerWithdraw selectByOrdNum(@Param("ordNum") String ordNum);

    ReferrerWithdraw getAndLock(@Param("id") Long id);

    List<ReferrerWithdrawVo> page(ReferrerWithdrawPageVo qryVo);

    int count(ReferrerWithdrawPageVo qryVo);
}
