package com.verificer.biz.biz.mapper;

import com.verificer.biz.biz.entity.Revise;

public interface ReviseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revise
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revise
     *
     * @mbg.generated
     */
    int insert(Revise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revise
     *
     * @mbg.generated
     */
    int insertSelective(Revise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revise
     *
     * @mbg.generated
     */
    Revise selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revise
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Revise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revise
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Revise record);
}
