package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.settle.SettleOrdVo;
import com.verificer.biz.beans.vo.settle.req.SettleOrdQryVo;
import com.verificer.biz.biz.entity.SettleOrder;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SettleOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_order
     *
     * @mbg.generated
     */
    int insert(SettleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_order
     *
     * @mbg.generated
     */
    int insertSelective(SettleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_order
     *
     * @mbg.generated
     */
    SettleOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SettleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settle_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SettleOrder record);

    List<SettleOrdVo> page(SettleOrdQryVo reqVo);

    int count(SettleOrdQryVo reqVo);

    SettleOrder selectUnCalFinishLimit1(@Param("year") Integer year,@Param("month") Integer month);

    SettleOrder selectByShopIdAndMonth(@Param("shopId") String shopId,@Param("year") Integer year,@Param("month") Integer month);

    SettleOrder selectByOrdNum(@Param("ordNum") String ordNum);

    SettleOrder getAndLock(@Param("id") Long id);
}
