package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.req.ShopListVo;
import com.verificer.biz.beans.vo.req.ShopPageVo;
import com.verificer.biz.biz.entity.Shop;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    Shop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shop record);

    List<Shop> list(ShopListVo qryVo);

    List<Shop> page(ShopPageVo qryVo);

    int count(ShopPageVo qryVo);

    Shop selectByNameLimit1(@Param("name") String name);

    void setParentIdNull(@Param("parentId") Long parentId);

    void setParentId(@Param("parentId")Long parentId,@Param("childIds") List<Long> childIds);
}
