package com.verificer.biz.biz.mapper;

import com.verificer.biz.biz.entity.Spec;

public interface SpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int insert(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int insertSelective(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    Spec selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Spec record);
}
