package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.shop.req.ShopStockQryVo;
import com.verificer.biz.beans.vo.stock.MerStockStaVo;
import com.verificer.biz.beans.vo.stock.MerStockVo;
import com.verificer.biz.beans.vo.stock.StaMaxMinVo;
import com.verificer.biz.beans.vo.stock.req.StockMerQryVo;
import com.verificer.biz.biz.entity.Stock;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    Stock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Stock record);

    Stock selectByRefIdAndSpecId(@Param("relId") String relId,@Param("specId") Long specId);

    Stock selectByIdForUpd(@Param("id") Long id);

    List<MerStockVo> selectByRelId(@Param("relId") String relId);

    List<MerStockStaVo> stockStaPage(StockMerQryVo qryVo);


    int stockStaCount(StockMerQryVo qryVo);

    List<MerStockVo> page(StockMerQryVo qryVo);

    int count(StockMerQryVo qryVo);

    List<MerStockVo> selectByRefIdAndGoodsId(@Param("relId") String relId,@Param("goodsId") Long goodsId);

    List<Stock> selectAll();
}
