package com.verificer.biz.biz.mapper;

import com.verificer.biz.beans.vo.req.UserPageVo;
import com.verificer.biz.biz.entity.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    User selectByPosMemberId(@Param("posMemberId") Long posMemberId);

    User getAndLock(@Param("id") Long id);

    List<User> page(UserPageVo qryVo);

    int count(UserPageVo qryVo);

    User selectByUid(@Param("uid") String uid);

    User selectByWxOpenId(@Param("wxOpenId") String wxOpenId);

    User getExpireMemberLimit1(@Param("now") Long now);
}
