package com.verificer.biz.biz.entity;

import java.math.BigDecimal;

public class AdjustOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.ord_num
     *
     * @mbg.generated
     */
    private String ordNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.spec_count
     *
     * @mbg.generated
     */
    private Integer specCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.from_id
     *
     * @mbg.generated
     */
    private String fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.from_name
     *
     * @mbg.generated
     */
    private String fromName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.to_id
     *
     * @mbg.generated
     */
    private String toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.to_name
     *
     * @mbg.generated
     */
    private String toName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.count
     *
     * @mbg.generated
     */
    private BigDecimal count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.real_count
     *
     * @mbg.generated
     */
    private BigDecimal realCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjust_order.finish_time
     *
     * @mbg.generated
     */
    private Long finishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.id
     *
     * @return the value of adjust_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.id
     *
     * @param id the value for adjust_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.ord_num
     *
     * @return the value of adjust_order.ord_num
     *
     * @mbg.generated
     */
    public String getOrdNum() {
        return ordNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.ord_num
     *
     * @param ordNum the value for adjust_order.ord_num
     *
     * @mbg.generated
     */
    public void setOrdNum(String ordNum) {
        this.ordNum = ordNum == null ? null : ordNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.spec_count
     *
     * @return the value of adjust_order.spec_count
     *
     * @mbg.generated
     */
    public Integer getSpecCount() {
        return specCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.spec_count
     *
     * @param specCount the value for adjust_order.spec_count
     *
     * @mbg.generated
     */
    public void setSpecCount(Integer specCount) {
        this.specCount = specCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.status
     *
     * @return the value of adjust_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.status
     *
     * @param status the value for adjust_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.type
     *
     * @return the value of adjust_order.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.type
     *
     * @param type the value for adjust_order.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.from_id
     *
     * @return the value of adjust_order.from_id
     *
     * @mbg.generated
     */
    public String getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.from_id
     *
     * @param fromId the value for adjust_order.from_id
     *
     * @mbg.generated
     */
    public void setFromId(String fromId) {
        this.fromId = fromId == null ? null : fromId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.from_name
     *
     * @return the value of adjust_order.from_name
     *
     * @mbg.generated
     */
    public String getFromName() {
        return fromName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.from_name
     *
     * @param fromName the value for adjust_order.from_name
     *
     * @mbg.generated
     */
    public void setFromName(String fromName) {
        this.fromName = fromName == null ? null : fromName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.to_id
     *
     * @return the value of adjust_order.to_id
     *
     * @mbg.generated
     */
    public String getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.to_id
     *
     * @param toId the value for adjust_order.to_id
     *
     * @mbg.generated
     */
    public void setToId(String toId) {
        this.toId = toId == null ? null : toId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.to_name
     *
     * @return the value of adjust_order.to_name
     *
     * @mbg.generated
     */
    public String getToName() {
        return toName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.to_name
     *
     * @param toName the value for adjust_order.to_name
     *
     * @mbg.generated
     */
    public void setToName(String toName) {
        this.toName = toName == null ? null : toName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.count
     *
     * @return the value of adjust_order.count
     *
     * @mbg.generated
     */
    public BigDecimal getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.count
     *
     * @param count the value for adjust_order.count
     *
     * @mbg.generated
     */
    public void setCount(BigDecimal count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.real_count
     *
     * @return the value of adjust_order.real_count
     *
     * @mbg.generated
     */
    public BigDecimal getRealCount() {
        return realCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.real_count
     *
     * @param realCount the value for adjust_order.real_count
     *
     * @mbg.generated
     */
    public void setRealCount(BigDecimal realCount) {
        this.realCount = realCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.create_time
     *
     * @return the value of adjust_order.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.create_time
     *
     * @param createTime the value for adjust_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjust_order.finish_time
     *
     * @return the value of adjust_order.finish_time
     *
     * @mbg.generated
     */
    public Long getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjust_order.finish_time
     *
     * @param finishTime the value for adjust_order.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Long finishTime) {
        this.finishTime = finishTime;
    }
}
