package com.verificer.biz.biz.entity;

public class Category {

    private Long id;

    private String name;

    private String shortName;

    private String logoImg;

    private String searchKey;

    private Long createTime;

    private Boolean delFlag;

    private Long delTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.short_name
     *
     * @return the value of category.short_name
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.short_name
     *
     * @param shortName the value for category.short_name
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.logo_img
     *
     * @return the value of category.logo_img
     *
     * @mbg.generated
     */
    public String getLogoImg() {
        return logoImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.logo_img
     *
     * @param logoImg the value for category.logo_img
     *
     * @mbg.generated
     */
    public void setLogoImg(String logoImg) {
        this.logoImg = logoImg == null ? null : logoImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.search_key
     *
     * @return the value of category.search_key
     *
     * @mbg.generated
     */
    public String getSearchKey() {
        return searchKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.search_key
     *
     * @param searchKey the value for category.search_key
     *
     * @mbg.generated
     */
    public void setSearchKey(String searchKey) {
        this.searchKey = searchKey == null ? null : searchKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.create_time
     *
     * @return the value of category.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.create_time
     *
     * @param createTime the value for category.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.del_flag
     *
     * @return the value of category.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.del_flag
     *
     * @param delFlag the value for category.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.del_time
     *
     * @return the value of category.del_time
     *
     * @mbg.generated
     */
    public Long getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.del_time
     *
     * @param delTime the value for category.del_time
     *
     * @mbg.generated
     */
    public void setDelTime(Long delTime) {
        this.delTime = delTime;
    }
}
