package com.verificer.biz.biz.entity;

public class DbgOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.ref_type
     *
     * @mbg.generated
     */
    private Integer refType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.ref_id
     *
     * @mbg.generated
     */
    private Long refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.pay_type
     *
     * @mbg.generated
     */
    private Long payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.pay_id
     *
     * @mbg.generated
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_type
     *
     * @mbg.generated
     */
    private Integer transitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_way_code
     *
     * @mbg.generated
     */
    private String transitWayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.receiver_addr
     *
     * @mbg.generated
     */
    private String receiverAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.activity_title
     *
     * @mbg.generated
     */
    private String activityTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.buyer_remark
     *
     * @mbg.generated
     */
    private String buyerRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_order_id
     *
     * @mbg.generated
     */
    private String transitOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_time
     *
     * @mbg.generated
     */
    private Long transitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_order_num
     *
     * @mbg.generated
     */
    private String transitOrderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.del_flag
     *
     * @mbg.generated
     */
    private Long delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.del_time
     *
     * @mbg.generated
     */
    private Long delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.take_code
     *
     * @mbg.generated
     */
    private String takeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.take_flag
     *
     * @mbg.generated
     */
    private Boolean takeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.take_time
     *
     * @mbg.generated
     */
    private Long takeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.id
     *
     * @return the value of dbg_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.id
     *
     * @param id the value for dbg_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.status
     *
     * @return the value of dbg_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.status
     *
     * @param status the value for dbg_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.order_type
     *
     * @return the value of dbg_order.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.order_type
     *
     * @param orderType the value for dbg_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.ref_type
     *
     * @return the value of dbg_order.ref_type
     *
     * @mbg.generated
     */
    public Integer getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.ref_type
     *
     * @param refType the value for dbg_order.ref_type
     *
     * @mbg.generated
     */
    public void setRefType(Integer refType) {
        this.refType = refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.ref_id
     *
     * @return the value of dbg_order.ref_id
     *
     * @mbg.generated
     */
    public Long getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.ref_id
     *
     * @param refId the value for dbg_order.ref_id
     *
     * @mbg.generated
     */
    public void setRefId(Long refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.pay_type
     *
     * @return the value of dbg_order.pay_type
     *
     * @mbg.generated
     */
    public Long getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.pay_type
     *
     * @param payType the value for dbg_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Long payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.pay_id
     *
     * @return the value of dbg_order.pay_id
     *
     * @mbg.generated
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.pay_id
     *
     * @param payId the value for dbg_order.pay_id
     *
     * @mbg.generated
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.user_id
     *
     * @return the value of dbg_order.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.user_id
     *
     * @param userId the value for dbg_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.user_name
     *
     * @return the value of dbg_order.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.user_name
     *
     * @param userName the value for dbg_order.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_type
     *
     * @return the value of dbg_order.transit_type
     *
     * @mbg.generated
     */
    public Integer getTransitType() {
        return transitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_type
     *
     * @param transitType the value for dbg_order.transit_type
     *
     * @mbg.generated
     */
    public void setTransitType(Integer transitType) {
        this.transitType = transitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_way_code
     *
     * @return the value of dbg_order.transit_way_code
     *
     * @mbg.generated
     */
    public String getTransitWayCode() {
        return transitWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_way_code
     *
     * @param transitWayCode the value for dbg_order.transit_way_code
     *
     * @mbg.generated
     */
    public void setTransitWayCode(String transitWayCode) {
        this.transitWayCode = transitWayCode == null ? null : transitWayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.receiver_name
     *
     * @return the value of dbg_order.receiver_name
     *
     * @mbg.generated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.receiver_name
     *
     * @param receiverName the value for dbg_order.receiver_name
     *
     * @mbg.generated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.receiver_mobile
     *
     * @return the value of dbg_order.receiver_mobile
     *
     * @mbg.generated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.receiver_mobile
     *
     * @param receiverMobile the value for dbg_order.receiver_mobile
     *
     * @mbg.generated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.receiver_addr
     *
     * @return the value of dbg_order.receiver_addr
     *
     * @mbg.generated
     */
    public String getReceiverAddr() {
        return receiverAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.receiver_addr
     *
     * @param receiverAddr the value for dbg_order.receiver_addr
     *
     * @mbg.generated
     */
    public void setReceiverAddr(String receiverAddr) {
        this.receiverAddr = receiverAddr == null ? null : receiverAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.activity_id
     *
     * @return the value of dbg_order.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.activity_id
     *
     * @param activityId the value for dbg_order.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.activity_title
     *
     * @return the value of dbg_order.activity_title
     *
     * @mbg.generated
     */
    public String getActivityTitle() {
        return activityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.activity_title
     *
     * @param activityTitle the value for dbg_order.activity_title
     *
     * @mbg.generated
     */
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle == null ? null : activityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.buyer_remark
     *
     * @return the value of dbg_order.buyer_remark
     *
     * @mbg.generated
     */
    public String getBuyerRemark() {
        return buyerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.buyer_remark
     *
     * @param buyerRemark the value for dbg_order.buyer_remark
     *
     * @mbg.generated
     */
    public void setBuyerRemark(String buyerRemark) {
        this.buyerRemark = buyerRemark == null ? null : buyerRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.create_time
     *
     * @return the value of dbg_order.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.create_time
     *
     * @param createTime the value for dbg_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.order_num
     *
     * @return the value of dbg_order.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.order_num
     *
     * @param orderNum the value for dbg_order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_order_id
     *
     * @return the value of dbg_order.transit_order_id
     *
     * @mbg.generated
     */
    public String getTransitOrderId() {
        return transitOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_order_id
     *
     * @param transitOrderId the value for dbg_order.transit_order_id
     *
     * @mbg.generated
     */
    public void setTransitOrderId(String transitOrderId) {
        this.transitOrderId = transitOrderId == null ? null : transitOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_time
     *
     * @return the value of dbg_order.transit_time
     *
     * @mbg.generated
     */
    public Long getTransitTime() {
        return transitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_time
     *
     * @param transitTime the value for dbg_order.transit_time
     *
     * @mbg.generated
     */
    public void setTransitTime(Long transitTime) {
        this.transitTime = transitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_order_num
     *
     * @return the value of dbg_order.transit_order_num
     *
     * @mbg.generated
     */
    public String getTransitOrderNum() {
        return transitOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_order_num
     *
     * @param transitOrderNum the value for dbg_order.transit_order_num
     *
     * @mbg.generated
     */
    public void setTransitOrderNum(String transitOrderNum) {
        this.transitOrderNum = transitOrderNum == null ? null : transitOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.del_flag
     *
     * @return the value of dbg_order.del_flag
     *
     * @mbg.generated
     */
    public Long getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.del_flag
     *
     * @param delFlag the value for dbg_order.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Long delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.del_time
     *
     * @return the value of dbg_order.del_time
     *
     * @mbg.generated
     */
    public Long getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.del_time
     *
     * @param delTime the value for dbg_order.del_time
     *
     * @mbg.generated
     */
    public void setDelTime(Long delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.take_code
     *
     * @return the value of dbg_order.take_code
     *
     * @mbg.generated
     */
    public String getTakeCode() {
        return takeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.take_code
     *
     * @param takeCode the value for dbg_order.take_code
     *
     * @mbg.generated
     */
    public void setTakeCode(String takeCode) {
        this.takeCode = takeCode == null ? null : takeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.take_flag
     *
     * @return the value of dbg_order.take_flag
     *
     * @mbg.generated
     */
    public Boolean getTakeFlag() {
        return takeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.take_flag
     *
     * @param takeFlag the value for dbg_order.take_flag
     *
     * @mbg.generated
     */
    public void setTakeFlag(Boolean takeFlag) {
        this.takeFlag = takeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.take_time
     *
     * @return the value of dbg_order.take_time
     *
     * @mbg.generated
     */
    public Long getTakeTime() {
        return takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.take_time
     *
     * @param takeTime the value for dbg_order.take_time
     *
     * @mbg.generated
     */
    public void setTakeTime(Long takeTime) {
        this.takeTime = takeTime;
    }
}
