package com.verificer.biz.biz.entity;

import java.math.BigDecimal;

public class DbgOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.root_order_id
     *
     * @mbg.generated
     */
    private Long rootOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.orig_order_id
     *
     * @mbg.generated
     */
    private Long origOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.rel_type
     *
     * @mbg.generated
     */
    private Integer relType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.rel_id
     *
     * @mbg.generated
     */
    private String relId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.ref_name
     *
     * @mbg.generated
     */
    private String refName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.member_discount_amount
     *
     * @mbg.generated
     */
    private BigDecimal memberDiscountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_fee
     *
     * @mbg.generated
     */
    private BigDecimal transitFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.real_amount
     *
     * @mbg.generated
     */
    private BigDecimal realAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.pay_type
     *
     * @mbg.generated
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.pay_id
     *
     * @mbg.generated
     */
    private Long payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.member_flag
     *
     * @mbg.generated
     */
    private Boolean memberFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_type
     *
     * @mbg.generated
     */
    private Integer transitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_compnay
     *
     * @mbg.generated
     */
    private String transitCompnay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.rc_addr_id
     *
     * @mbg.generated
     */
    private Long rcAddrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.rc_name
     *
     * @mbg.generated
     */
    private String rcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.rc_mobile
     *
     * @mbg.generated
     */
    private String rcMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.rc_full_addr
     *
     * @mbg.generated
     */
    private String rcFullAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.activity_title
     *
     * @mbg.generated
     */
    private String activityTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.buyer_remark
     *
     * @mbg.generated
     */
    private String buyerRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.evaluate_time
     *
     * @mbg.generated
     */
    private Long evaluateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_order_id
     *
     * @mbg.generated
     */
    private String transitOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_time
     *
     * @mbg.generated
     */
    private Long transitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_rc_time
     *
     * @mbg.generated
     */
    private Long transitRcTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_user_confirm_time
     *
     * @mbg.generated
     */
    private Long transitUserConfirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.transit_order_num
     *
     * @mbg.generated
     */
    private String transitOrderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.del_time
     *
     * @mbg.generated
     */
    private Long delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.take_code
     *
     * @mbg.generated
     */
    private String takeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.take_time
     *
     * @mbg.generated
     */
    private Long takeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.write_to_db_time
     *
     * @mbg.generated
     */
    private Long writeToDbTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.pos_ord_id
     *
     * @mbg.generated
     */
    private Long posOrdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.pos_cashier_uid
     *
     * @mbg.generated
     */
    private Long posCashierUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.pos_member_uid
     *
     * @mbg.generated
     */
    private Long posMemberUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbg_order.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.id
     *
     * @return the value of dbg_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.id
     *
     * @param id the value for dbg_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.status
     *
     * @return the value of dbg_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.status
     *
     * @param status the value for dbg_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.root_order_id
     *
     * @return the value of dbg_order.root_order_id
     *
     * @mbg.generated
     */
    public Long getRootOrderId() {
        return rootOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.root_order_id
     *
     * @param rootOrderId the value for dbg_order.root_order_id
     *
     * @mbg.generated
     */
    public void setRootOrderId(Long rootOrderId) {
        this.rootOrderId = rootOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.orig_order_id
     *
     * @return the value of dbg_order.orig_order_id
     *
     * @mbg.generated
     */
    public Long getOrigOrderId() {
        return origOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.orig_order_id
     *
     * @param origOrderId the value for dbg_order.orig_order_id
     *
     * @mbg.generated
     */
    public void setOrigOrderId(Long origOrderId) {
        this.origOrderId = origOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.order_type
     *
     * @return the value of dbg_order.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.order_type
     *
     * @param orderType the value for dbg_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.rel_type
     *
     * @return the value of dbg_order.rel_type
     *
     * @mbg.generated
     */
    public Integer getRelType() {
        return relType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.rel_type
     *
     * @param relType the value for dbg_order.rel_type
     *
     * @mbg.generated
     */
    public void setRelType(Integer relType) {
        this.relType = relType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.rel_id
     *
     * @return the value of dbg_order.rel_id
     *
     * @mbg.generated
     */
    public String getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.rel_id
     *
     * @param relId the value for dbg_order.rel_id
     *
     * @mbg.generated
     */
    public void setRelId(String relId) {
        this.relId = relId == null ? null : relId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.ref_name
     *
     * @return the value of dbg_order.ref_name
     *
     * @mbg.generated
     */
    public String getRefName() {
        return refName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.ref_name
     *
     * @param refName the value for dbg_order.ref_name
     *
     * @mbg.generated
     */
    public void setRefName(String refName) {
        this.refName = refName == null ? null : refName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.total_amount
     *
     * @return the value of dbg_order.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.total_amount
     *
     * @param totalAmount the value for dbg_order.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.member_discount_amount
     *
     * @return the value of dbg_order.member_discount_amount
     *
     * @mbg.generated
     */
    public BigDecimal getMemberDiscountAmount() {
        return memberDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.member_discount_amount
     *
     * @param memberDiscountAmount the value for dbg_order.member_discount_amount
     *
     * @mbg.generated
     */
    public void setMemberDiscountAmount(BigDecimal memberDiscountAmount) {
        this.memberDiscountAmount = memberDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_fee
     *
     * @return the value of dbg_order.transit_fee
     *
     * @mbg.generated
     */
    public BigDecimal getTransitFee() {
        return transitFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_fee
     *
     * @param transitFee the value for dbg_order.transit_fee
     *
     * @mbg.generated
     */
    public void setTransitFee(BigDecimal transitFee) {
        this.transitFee = transitFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.amount
     *
     * @return the value of dbg_order.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.amount
     *
     * @param amount the value for dbg_order.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.real_amount
     *
     * @return the value of dbg_order.real_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRealAmount() {
        return realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.real_amount
     *
     * @param realAmount the value for dbg_order.real_amount
     *
     * @mbg.generated
     */
    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.pay_type
     *
     * @return the value of dbg_order.pay_type
     *
     * @mbg.generated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.pay_type
     *
     * @param payType the value for dbg_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.pay_id
     *
     * @return the value of dbg_order.pay_id
     *
     * @mbg.generated
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.pay_id
     *
     * @param payId the value for dbg_order.pay_id
     *
     * @mbg.generated
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.member_flag
     *
     * @return the value of dbg_order.member_flag
     *
     * @mbg.generated
     */
    public Boolean getMemberFlag() {
        return memberFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.member_flag
     *
     * @param memberFlag the value for dbg_order.member_flag
     *
     * @mbg.generated
     */
    public void setMemberFlag(Boolean memberFlag) {
        this.memberFlag = memberFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.user_id
     *
     * @return the value of dbg_order.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.user_id
     *
     * @param userId the value for dbg_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.user_name
     *
     * @return the value of dbg_order.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.user_name
     *
     * @param userName the value for dbg_order.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_type
     *
     * @return the value of dbg_order.transit_type
     *
     * @mbg.generated
     */
    public Integer getTransitType() {
        return transitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_type
     *
     * @param transitType the value for dbg_order.transit_type
     *
     * @mbg.generated
     */
    public void setTransitType(Integer transitType) {
        this.transitType = transitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_compnay
     *
     * @return the value of dbg_order.transit_compnay
     *
     * @mbg.generated
     */
    public String getTransitCompnay() {
        return transitCompnay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_compnay
     *
     * @param transitCompnay the value for dbg_order.transit_compnay
     *
     * @mbg.generated
     */
    public void setTransitCompnay(String transitCompnay) {
        this.transitCompnay = transitCompnay == null ? null : transitCompnay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.rc_addr_id
     *
     * @return the value of dbg_order.rc_addr_id
     *
     * @mbg.generated
     */
    public Long getRcAddrId() {
        return rcAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.rc_addr_id
     *
     * @param rcAddrId the value for dbg_order.rc_addr_id
     *
     * @mbg.generated
     */
    public void setRcAddrId(Long rcAddrId) {
        this.rcAddrId = rcAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.rc_name
     *
     * @return the value of dbg_order.rc_name
     *
     * @mbg.generated
     */
    public String getRcName() {
        return rcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.rc_name
     *
     * @param rcName the value for dbg_order.rc_name
     *
     * @mbg.generated
     */
    public void setRcName(String rcName) {
        this.rcName = rcName == null ? null : rcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.rc_mobile
     *
     * @return the value of dbg_order.rc_mobile
     *
     * @mbg.generated
     */
    public String getRcMobile() {
        return rcMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.rc_mobile
     *
     * @param rcMobile the value for dbg_order.rc_mobile
     *
     * @mbg.generated
     */
    public void setRcMobile(String rcMobile) {
        this.rcMobile = rcMobile == null ? null : rcMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.rc_full_addr
     *
     * @return the value of dbg_order.rc_full_addr
     *
     * @mbg.generated
     */
    public String getRcFullAddr() {
        return rcFullAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.rc_full_addr
     *
     * @param rcFullAddr the value for dbg_order.rc_full_addr
     *
     * @mbg.generated
     */
    public void setRcFullAddr(String rcFullAddr) {
        this.rcFullAddr = rcFullAddr == null ? null : rcFullAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.activity_id
     *
     * @return the value of dbg_order.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.activity_id
     *
     * @param activityId the value for dbg_order.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.activity_title
     *
     * @return the value of dbg_order.activity_title
     *
     * @mbg.generated
     */
    public String getActivityTitle() {
        return activityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.activity_title
     *
     * @param activityTitle the value for dbg_order.activity_title
     *
     * @mbg.generated
     */
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle == null ? null : activityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.buyer_remark
     *
     * @return the value of dbg_order.buyer_remark
     *
     * @mbg.generated
     */
    public String getBuyerRemark() {
        return buyerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.buyer_remark
     *
     * @param buyerRemark the value for dbg_order.buyer_remark
     *
     * @mbg.generated
     */
    public void setBuyerRemark(String buyerRemark) {
        this.buyerRemark = buyerRemark == null ? null : buyerRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.create_time
     *
     * @return the value of dbg_order.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.create_time
     *
     * @param createTime the value for dbg_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.evaluate_time
     *
     * @return the value of dbg_order.evaluate_time
     *
     * @mbg.generated
     */
    public Long getEvaluateTime() {
        return evaluateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.evaluate_time
     *
     * @param evaluateTime the value for dbg_order.evaluate_time
     *
     * @mbg.generated
     */
    public void setEvaluateTime(Long evaluateTime) {
        this.evaluateTime = evaluateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.order_num
     *
     * @return the value of dbg_order.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.order_num
     *
     * @param orderNum the value for dbg_order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_order_id
     *
     * @return the value of dbg_order.transit_order_id
     *
     * @mbg.generated
     */
    public String getTransitOrderId() {
        return transitOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_order_id
     *
     * @param transitOrderId the value for dbg_order.transit_order_id
     *
     * @mbg.generated
     */
    public void setTransitOrderId(String transitOrderId) {
        this.transitOrderId = transitOrderId == null ? null : transitOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_time
     *
     * @return the value of dbg_order.transit_time
     *
     * @mbg.generated
     */
    public Long getTransitTime() {
        return transitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_time
     *
     * @param transitTime the value for dbg_order.transit_time
     *
     * @mbg.generated
     */
    public void setTransitTime(Long transitTime) {
        this.transitTime = transitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_rc_time
     *
     * @return the value of dbg_order.transit_rc_time
     *
     * @mbg.generated
     */
    public Long getTransitRcTime() {
        return transitRcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_rc_time
     *
     * @param transitRcTime the value for dbg_order.transit_rc_time
     *
     * @mbg.generated
     */
    public void setTransitRcTime(Long transitRcTime) {
        this.transitRcTime = transitRcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_user_confirm_time
     *
     * @return the value of dbg_order.transit_user_confirm_time
     *
     * @mbg.generated
     */
    public Long getTransitUserConfirmTime() {
        return transitUserConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_user_confirm_time
     *
     * @param transitUserConfirmTime the value for dbg_order.transit_user_confirm_time
     *
     * @mbg.generated
     */
    public void setTransitUserConfirmTime(Long transitUserConfirmTime) {
        this.transitUserConfirmTime = transitUserConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.transit_order_num
     *
     * @return the value of dbg_order.transit_order_num
     *
     * @mbg.generated
     */
    public String getTransitOrderNum() {
        return transitOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.transit_order_num
     *
     * @param transitOrderNum the value for dbg_order.transit_order_num
     *
     * @mbg.generated
     */
    public void setTransitOrderNum(String transitOrderNum) {
        this.transitOrderNum = transitOrderNum == null ? null : transitOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.del_flag
     *
     * @return the value of dbg_order.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.del_flag
     *
     * @param delFlag the value for dbg_order.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.del_time
     *
     * @return the value of dbg_order.del_time
     *
     * @mbg.generated
     */
    public Long getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.del_time
     *
     * @param delTime the value for dbg_order.del_time
     *
     * @mbg.generated
     */
    public void setDelTime(Long delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.take_code
     *
     * @return the value of dbg_order.take_code
     *
     * @mbg.generated
     */
    public String getTakeCode() {
        return takeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.take_code
     *
     * @param takeCode the value for dbg_order.take_code
     *
     * @mbg.generated
     */
    public void setTakeCode(String takeCode) {
        this.takeCode = takeCode == null ? null : takeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.take_time
     *
     * @return the value of dbg_order.take_time
     *
     * @mbg.generated
     */
    public Long getTakeTime() {
        return takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.take_time
     *
     * @param takeTime the value for dbg_order.take_time
     *
     * @mbg.generated
     */
    public void setTakeTime(Long takeTime) {
        this.takeTime = takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.write_to_db_time
     *
     * @return the value of dbg_order.write_to_db_time
     *
     * @mbg.generated
     */
    public Long getWriteToDbTime() {
        return writeToDbTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.write_to_db_time
     *
     * @param writeToDbTime the value for dbg_order.write_to_db_time
     *
     * @mbg.generated
     */
    public void setWriteToDbTime(Long writeToDbTime) {
        this.writeToDbTime = writeToDbTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.pos_ord_id
     *
     * @return the value of dbg_order.pos_ord_id
     *
     * @mbg.generated
     */
    public Long getPosOrdId() {
        return posOrdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.pos_ord_id
     *
     * @param posOrdId the value for dbg_order.pos_ord_id
     *
     * @mbg.generated
     */
    public void setPosOrdId(Long posOrdId) {
        this.posOrdId = posOrdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.pos_cashier_uid
     *
     * @return the value of dbg_order.pos_cashier_uid
     *
     * @mbg.generated
     */
    public Long getPosCashierUid() {
        return posCashierUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.pos_cashier_uid
     *
     * @param posCashierUid the value for dbg_order.pos_cashier_uid
     *
     * @mbg.generated
     */
    public void setPosCashierUid(Long posCashierUid) {
        this.posCashierUid = posCashierUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.pos_member_uid
     *
     * @return the value of dbg_order.pos_member_uid
     *
     * @mbg.generated
     */
    public Long getPosMemberUid() {
        return posMemberUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.pos_member_uid
     *
     * @param posMemberUid the value for dbg_order.pos_member_uid
     *
     * @mbg.generated
     */
    public void setPosMemberUid(Long posMemberUid) {
        this.posMemberUid = posMemberUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbg_order.version
     *
     * @return the value of dbg_order.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbg_order.version
     *
     * @param version the value for dbg_order.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}
