package com.verificer.biz.biz.entity;

import java.math.BigDecimal;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img_list
     *
     * @mbg.generated
     */
    private String imgList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.key_word
     *
     * @mbg.generated
     */
    private String keyWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.search_key
     *
     * @mbg.generated
     */
    private String searchKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.free_shipping_flag
     *
     * @mbg.generated
     */
    private Boolean freeShippingFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.weight
     *
     * @mbg.generated
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.volume
     *
     * @mbg.generated
     */
    private BigDecimal volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.max_limit_count
     *
     * @mbg.generated
     */
    private BigDecimal maxLimitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.min_limit_count
     *
     * @mbg.generated
     */
    private BigDecimal minLimitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale_flag
     *
     * @mbg.generated
     */
    private Boolean saleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale_time_out_flag
     *
     * @mbg.generated
     */
    private Boolean saleTimeOutFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.stop_sale_time
     *
     * @mbg.generated
     */
    private Long stopSaleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.del_time
     *
     * @mbg.generated
     */
    private Long delTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.rubbish_flag
     *
     * @mbg.generated
     */
    private Boolean rubbishFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.rubbish_time
     *
     * @mbg.generated
     */
    private Long rubbishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sku_flag
     *
     * @mbg.generated
     */
    private Boolean skuFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pos_by_weight_flag
     *
     * @mbg.generated
     */
    private Boolean posByWeightFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.category_id
     *
     * @return the value of goods.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.category_id
     *
     * @param categoryId the value for goods.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brand_id
     *
     * @return the value of goods.brand_id
     *
     * @mbg.generated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brand_id
     *
     * @param brandId the value for goods.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img_list
     *
     * @return the value of goods.img_list
     *
     * @mbg.generated
     */
    public String getImgList() {
        return imgList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img_list
     *
     * @param imgList the value for goods.img_list
     *
     * @mbg.generated
     */
    public void setImgList(String imgList) {
        this.imgList = imgList == null ? null : imgList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.key_word
     *
     * @return the value of goods.key_word
     *
     * @mbg.generated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.key_word
     *
     * @param keyWord the value for goods.key_word
     *
     * @mbg.generated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.search_key
     *
     * @return the value of goods.search_key
     *
     * @mbg.generated
     */
    public String getSearchKey() {
        return searchKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.search_key
     *
     * @param searchKey the value for goods.search_key
     *
     * @mbg.generated
     */
    public void setSearchKey(String searchKey) {
        this.searchKey = searchKey == null ? null : searchKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.free_shipping_flag
     *
     * @return the value of goods.free_shipping_flag
     *
     * @mbg.generated
     */
    public Boolean getFreeShippingFlag() {
        return freeShippingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.free_shipping_flag
     *
     * @param freeShippingFlag the value for goods.free_shipping_flag
     *
     * @mbg.generated
     */
    public void setFreeShippingFlag(Boolean freeShippingFlag) {
        this.freeShippingFlag = freeShippingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.weight
     *
     * @return the value of goods.weight
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.weight
     *
     * @param weight the value for goods.weight
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.volume
     *
     * @return the value of goods.volume
     *
     * @mbg.generated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.volume
     *
     * @param volume the value for goods.volume
     *
     * @mbg.generated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.max_limit_count
     *
     * @return the value of goods.max_limit_count
     *
     * @mbg.generated
     */
    public BigDecimal getMaxLimitCount() {
        return maxLimitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.max_limit_count
     *
     * @param maxLimitCount the value for goods.max_limit_count
     *
     * @mbg.generated
     */
    public void setMaxLimitCount(BigDecimal maxLimitCount) {
        this.maxLimitCount = maxLimitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.min_limit_count
     *
     * @return the value of goods.min_limit_count
     *
     * @mbg.generated
     */
    public BigDecimal getMinLimitCount() {
        return minLimitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.min_limit_count
     *
     * @param minLimitCount the value for goods.min_limit_count
     *
     * @mbg.generated
     */
    public void setMinLimitCount(BigDecimal minLimitCount) {
        this.minLimitCount = minLimitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.unit
     *
     * @return the value of goods.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.unit
     *
     * @param unit the value for goods.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale_flag
     *
     * @return the value of goods.sale_flag
     *
     * @mbg.generated
     */
    public Boolean getSaleFlag() {
        return saleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale_flag
     *
     * @param saleFlag the value for goods.sale_flag
     *
     * @mbg.generated
     */
    public void setSaleFlag(Boolean saleFlag) {
        this.saleFlag = saleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale_time_out_flag
     *
     * @return the value of goods.sale_time_out_flag
     *
     * @mbg.generated
     */
    public Boolean getSaleTimeOutFlag() {
        return saleTimeOutFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale_time_out_flag
     *
     * @param saleTimeOutFlag the value for goods.sale_time_out_flag
     *
     * @mbg.generated
     */
    public void setSaleTimeOutFlag(Boolean saleTimeOutFlag) {
        this.saleTimeOutFlag = saleTimeOutFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.stop_sale_time
     *
     * @return the value of goods.stop_sale_time
     *
     * @mbg.generated
     */
    public Long getStopSaleTime() {
        return stopSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.stop_sale_time
     *
     * @param stopSaleTime the value for goods.stop_sale_time
     *
     * @mbg.generated
     */
    public void setStopSaleTime(Long stopSaleTime) {
        this.stopSaleTime = stopSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.detail
     *
     * @return the value of goods.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.detail
     *
     * @param detail the value for goods.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.del_flag
     *
     * @return the value of goods.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.del_flag
     *
     * @param delFlag the value for goods.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.del_time
     *
     * @return the value of goods.del_time
     *
     * @mbg.generated
     */
    public Long getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.del_time
     *
     * @param delTime the value for goods.del_time
     *
     * @mbg.generated
     */
    public void setDelTime(Long delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.rubbish_flag
     *
     * @return the value of goods.rubbish_flag
     *
     * @mbg.generated
     */
    public Boolean getRubbishFlag() {
        return rubbishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.rubbish_flag
     *
     * @param rubbishFlag the value for goods.rubbish_flag
     *
     * @mbg.generated
     */
    public void setRubbishFlag(Boolean rubbishFlag) {
        this.rubbishFlag = rubbishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.rubbish_time
     *
     * @return the value of goods.rubbish_time
     *
     * @mbg.generated
     */
    public Long getRubbishTime() {
        return rubbishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.rubbish_time
     *
     * @param rubbishTime the value for goods.rubbish_time
     *
     * @mbg.generated
     */
    public void setRubbishTime(Long rubbishTime) {
        this.rubbishTime = rubbishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sku_flag
     *
     * @return the value of goods.sku_flag
     *
     * @mbg.generated
     */
    public Boolean getSkuFlag() {
        return skuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sku_flag
     *
     * @param skuFlag the value for goods.sku_flag
     *
     * @mbg.generated
     */
    public void setSkuFlag(Boolean skuFlag) {
        this.skuFlag = skuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pos_by_weight_flag
     *
     * @return the value of goods.pos_by_weight_flag
     *
     * @mbg.generated
     */
    public Boolean getPosByWeightFlag() {
        return posByWeightFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pos_by_weight_flag
     *
     * @param posByWeightFlag the value for goods.pos_by_weight_flag
     *
     * @mbg.generated
     */
    public void setPosByWeightFlag(Boolean posByWeightFlag) {
        this.posByWeightFlag = posByWeightFlag;
    }
}
