package com.verificer.biz.biz.entity;

import java.math.BigDecimal;

public class PlaIncomeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.ord_id
     *
     * @mbg.generated
     */
    private Long ordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.ord_num
     *
     * @mbg.generated
     */
    private String ordNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.income_flag
     *
     * @mbg.generated
     */
    private Boolean incomeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_income_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.id
     *
     * @return the value of pla_income_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.id
     *
     * @param id the value for pla_income_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.type
     *
     * @return the value of pla_income_log.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.type
     *
     * @param type the value for pla_income_log.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.shop_id
     *
     * @return the value of pla_income_log.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.shop_id
     *
     * @param shopId the value for pla_income_log.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.ord_id
     *
     * @return the value of pla_income_log.ord_id
     *
     * @mbg.generated
     */
    public Long getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.ord_id
     *
     * @param ordId the value for pla_income_log.ord_id
     *
     * @mbg.generated
     */
    public void setOrdId(Long ordId) {
        this.ordId = ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.ord_num
     *
     * @return the value of pla_income_log.ord_num
     *
     * @mbg.generated
     */
    public String getOrdNum() {
        return ordNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.ord_num
     *
     * @param ordNum the value for pla_income_log.ord_num
     *
     * @mbg.generated
     */
    public void setOrdNum(String ordNum) {
        this.ordNum = ordNum == null ? null : ordNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.amount
     *
     * @return the value of pla_income_log.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.amount
     *
     * @param amount the value for pla_income_log.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.income_flag
     *
     * @return the value of pla_income_log.income_flag
     *
     * @mbg.generated
     */
    public Boolean getIncomeFlag() {
        return incomeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.income_flag
     *
     * @param incomeFlag the value for pla_income_log.income_flag
     *
     * @mbg.generated
     */
    public void setIncomeFlag(Boolean incomeFlag) {
        this.incomeFlag = incomeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.create_time
     *
     * @return the value of pla_income_log.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.create_time
     *
     * @param createTime the value for pla_income_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_income_log.remark
     *
     * @return the value of pla_income_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_income_log.remark
     *
     * @param remark the value for pla_income_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}
