package com.verificer.biz.biz.entity;

public class PosPayItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_pay_item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_pay_item.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_pay_item.pay_type_code
     *
     * @mbg.generated
     */
    private String payTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_pay_item.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_pay_item.id
     *
     * @return the value of pos_pay_item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_pay_item.id
     *
     * @param id the value for pos_pay_item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_pay_item.order_id
     *
     * @return the value of pos_pay_item.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_pay_item.order_id
     *
     * @param orderId the value for pos_pay_item.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_pay_item.pay_type_code
     *
     * @return the value of pos_pay_item.pay_type_code
     *
     * @mbg.generated
     */
    public String getPayTypeCode() {
        return payTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_pay_item.pay_type_code
     *
     * @param payTypeCode the value for pos_pay_item.pay_type_code
     *
     * @mbg.generated
     */
    public void setPayTypeCode(String payTypeCode) {
        this.payTypeCode = payTypeCode == null ? null : payTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_pay_item.amount
     *
     * @return the value of pos_pay_item.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_pay_item.amount
     *
     * @param amount the value for pos_pay_item.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }
}
