package com.verificer.biz.biz.entity;

public class PosSyncTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.rel_id
     *
     * @mbg.generated
     */
    private Long relId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.req_data
     *
     * @mbg.generated
     */
    private String reqData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.retry_count
     *
     * @mbg.generated
     */
    private Integer retryCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.next_retry_time
     *
     * @mbg.generated
     */
    private Long nextRetryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.last_call_time
     *
     * @mbg.generated
     */
    private Long lastCallTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.finish_time
     *
     * @mbg.generated
     */
    private Long finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_sync_task.err_msg
     *
     * @mbg.generated
     */
    private String errMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.id
     *
     * @return the value of pos_sync_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.id
     *
     * @param id the value for pos_sync_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.version
     *
     * @return the value of pos_sync_task.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.version
     *
     * @param version the value for pos_sync_task.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.rel_id
     *
     * @return the value of pos_sync_task.rel_id
     *
     * @mbg.generated
     */
    public Long getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.rel_id
     *
     * @param relId the value for pos_sync_task.rel_id
     *
     * @mbg.generated
     */
    public void setRelId(Long relId) {
        this.relId = relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.type
     *
     * @return the value of pos_sync_task.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.type
     *
     * @param type the value for pos_sync_task.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.shop_id
     *
     * @return the value of pos_sync_task.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.shop_id
     *
     * @param shopId the value for pos_sync_task.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.req_data
     *
     * @return the value of pos_sync_task.req_data
     *
     * @mbg.generated
     */
    public String getReqData() {
        return reqData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.req_data
     *
     * @param reqData the value for pos_sync_task.req_data
     *
     * @mbg.generated
     */
    public void setReqData(String reqData) {
        this.reqData = reqData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.status
     *
     * @return the value of pos_sync_task.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.status
     *
     * @param status the value for pos_sync_task.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.retry_count
     *
     * @return the value of pos_sync_task.retry_count
     *
     * @mbg.generated
     */
    public Integer getRetryCount() {
        return retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.retry_count
     *
     * @param retryCount the value for pos_sync_task.retry_count
     *
     * @mbg.generated
     */
    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.next_retry_time
     *
     * @return the value of pos_sync_task.next_retry_time
     *
     * @mbg.generated
     */
    public Long getNextRetryTime() {
        return nextRetryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.next_retry_time
     *
     * @param nextRetryTime the value for pos_sync_task.next_retry_time
     *
     * @mbg.generated
     */
    public void setNextRetryTime(Long nextRetryTime) {
        this.nextRetryTime = nextRetryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.create_time
     *
     * @return the value of pos_sync_task.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.create_time
     *
     * @param createTime the value for pos_sync_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.last_call_time
     *
     * @return the value of pos_sync_task.last_call_time
     *
     * @mbg.generated
     */
    public Long getLastCallTime() {
        return lastCallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.last_call_time
     *
     * @param lastCallTime the value for pos_sync_task.last_call_time
     *
     * @mbg.generated
     */
    public void setLastCallTime(Long lastCallTime) {
        this.lastCallTime = lastCallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.finish_time
     *
     * @return the value of pos_sync_task.finish_time
     *
     * @mbg.generated
     */
    public Long getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.finish_time
     *
     * @param finishTime the value for pos_sync_task.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Long finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_sync_task.err_msg
     *
     * @return the value of pos_sync_task.err_msg
     *
     * @mbg.generated
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_sync_task.err_msg
     *
     * @param errMsg the value for pos_sync_task.err_msg
     *
     * @mbg.generated
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }
}
