package com.verificer.biz.biz.entity;

import java.math.BigDecimal;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.spec_id
     *
     * @mbg.generated
     */
    private Long specId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sku_flag
     *
     * @mbg.generated
     */
    private Boolean skuFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stage_flag
     *
     * @mbg.generated
     */
    private Boolean stageFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.rel_id
     *
     * @mbg.generated
     */
    private String relId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.count
     *
     * @mbg.generated
     */
    private BigDecimal count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.goods_id
     *
     * @return the value of stock.goods_id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.goods_id
     *
     * @param goodsId the value for stock.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.spec_id
     *
     * @return the value of stock.spec_id
     *
     * @mbg.generated
     */
    public Long getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.spec_id
     *
     * @param specId the value for stock.spec_id
     *
     * @mbg.generated
     */
    public void setSpecId(Long specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sku_flag
     *
     * @return the value of stock.sku_flag
     *
     * @mbg.generated
     */
    public Boolean getSkuFlag() {
        return skuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sku_flag
     *
     * @param skuFlag the value for stock.sku_flag
     *
     * @mbg.generated
     */
    public void setSkuFlag(Boolean skuFlag) {
        this.skuFlag = skuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stage_flag
     *
     * @return the value of stock.stage_flag
     *
     * @mbg.generated
     */
    public Boolean getStageFlag() {
        return stageFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stage_flag
     *
     * @param stageFlag the value for stock.stage_flag
     *
     * @mbg.generated
     */
    public void setStageFlag(Boolean stageFlag) {
        this.stageFlag = stageFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.rel_id
     *
     * @return the value of stock.rel_id
     *
     * @mbg.generated
     */
    public String getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.rel_id
     *
     * @param relId the value for stock.rel_id
     *
     * @mbg.generated
     */
    public void setRelId(String relId) {
        this.relId = relId == null ? null : relId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.count
     *
     * @return the value of stock.count
     *
     * @mbg.generated
     */
    public BigDecimal getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.count
     *
     * @param count the value for stock.count
     *
     * @mbg.generated
     */
    public void setCount(BigDecimal count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.create_time
     *
     * @return the value of stock.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.create_time
     *
     * @param createTime the value for stock.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
