package com.verificer.biz.biz.entity;

import java.math.BigDecimal;

public class StockLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.stock_id
     *
     * @mbg.generated
     */
    private Long stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.spec_id
     *
     * @mbg.generated
     */
    private Long specId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.op_type
     *
     * @mbg.generated
     */
    private Integer opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.rel_id
     *
     * @mbg.generated
     */
    private String relId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.count
     *
     * @mbg.generated
     */
    private BigDecimal count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.before_stock
     *
     * @mbg.generated
     */
    private BigDecimal beforeStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.after_stock
     *
     * @mbg.generated
     */
    private BigDecimal afterStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.id
     *
     * @return the value of stock_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.id
     *
     * @param id the value for stock_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.stock_id
     *
     * @return the value of stock_log.stock_id
     *
     * @mbg.generated
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.stock_id
     *
     * @param stockId the value for stock_log.stock_id
     *
     * @mbg.generated
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.goods_id
     *
     * @return the value of stock_log.goods_id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.goods_id
     *
     * @param goodsId the value for stock_log.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.spec_id
     *
     * @return the value of stock_log.spec_id
     *
     * @mbg.generated
     */
    public Long getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.spec_id
     *
     * @param specId the value for stock_log.spec_id
     *
     * @mbg.generated
     */
    public void setSpecId(Long specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.op_type
     *
     * @return the value of stock_log.op_type
     *
     * @mbg.generated
     */
    public Integer getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.op_type
     *
     * @param opType the value for stock_log.op_type
     *
     * @mbg.generated
     */
    public void setOpType(Integer opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.rel_id
     *
     * @return the value of stock_log.rel_id
     *
     * @mbg.generated
     */
    public String getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.rel_id
     *
     * @param relId the value for stock_log.rel_id
     *
     * @mbg.generated
     */
    public void setRelId(String relId) {
        this.relId = relId == null ? null : relId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.count
     *
     * @return the value of stock_log.count
     *
     * @mbg.generated
     */
    public BigDecimal getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.count
     *
     * @param count the value for stock_log.count
     *
     * @mbg.generated
     */
    public void setCount(BigDecimal count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.before_stock
     *
     * @return the value of stock_log.before_stock
     *
     * @mbg.generated
     */
    public BigDecimal getBeforeStock() {
        return beforeStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.before_stock
     *
     * @param beforeStock the value for stock_log.before_stock
     *
     * @mbg.generated
     */
    public void setBeforeStock(BigDecimal beforeStock) {
        this.beforeStock = beforeStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.after_stock
     *
     * @return the value of stock_log.after_stock
     *
     * @mbg.generated
     */
    public BigDecimal getAfterStock() {
        return afterStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.after_stock
     *
     * @param afterStock the value for stock_log.after_stock
     *
     * @mbg.generated
     */
    public void setAfterStock(BigDecimal afterStock) {
        this.afterStock = afterStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.create_time
     *
     * @return the value of stock_log.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.create_time
     *
     * @param createTime the value for stock_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_log.remark
     *
     * @return the value of stock_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_log.remark
     *
     * @param remark the value for stock_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}
