package com.verificer.biz.biz.entity;

import java.math.BigDecimal;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.member_flag
     *
     * @mbg.generated
     */
    private Byte memberFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.member_s_time
     *
     * @mbg.generated
     */
    private Long memberSTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.member_e_time
     *
     * @mbg.generated
     */
    private Long memberETime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_time
     *
     * @mbg.generated
     */
    private Long regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.referrer_flag
     *
     * @mbg.generated
     */
    private Byte referrerFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_count
     *
     * @mbg.generated
     */
    private Integer inviteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_commission
     *
     * @mbg.generated
     */
    private BigDecimal inviteCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sum_order_amount
     *
     * @mbg.generated
     */
    private BigDecimal sumOrderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sum_order_count
     *
     * @mbg.generated
     */
    private Integer sumOrderCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.member_flag
     *
     * @return the value of user.member_flag
     *
     * @mbg.generated
     */
    public Byte getMemberFlag() {
        return memberFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.member_flag
     *
     * @param memberFlag the value for user.member_flag
     *
     * @mbg.generated
     */
    public void setMemberFlag(Byte memberFlag) {
        this.memberFlag = memberFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.member_s_time
     *
     * @return the value of user.member_s_time
     *
     * @mbg.generated
     */
    public Long getMemberSTime() {
        return memberSTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.member_s_time
     *
     * @param memberSTime the value for user.member_s_time
     *
     * @mbg.generated
     */
    public void setMemberSTime(Long memberSTime) {
        this.memberSTime = memberSTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.member_e_time
     *
     * @return the value of user.member_e_time
     *
     * @mbg.generated
     */
    public Long getMemberETime() {
        return memberETime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.member_e_time
     *
     * @param memberETime the value for user.member_e_time
     *
     * @mbg.generated
     */
    public void setMemberETime(Long memberETime) {
        this.memberETime = memberETime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_time
     *
     * @return the value of user.reg_time
     *
     * @mbg.generated
     */
    public Long getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_time
     *
     * @param regTime the value for user.reg_time
     *
     * @mbg.generated
     */
    public void setRegTime(Long regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.referrer_flag
     *
     * @return the value of user.referrer_flag
     *
     * @mbg.generated
     */
    public Byte getReferrerFlag() {
        return referrerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.referrer_flag
     *
     * @param referrerFlag the value for user.referrer_flag
     *
     * @mbg.generated
     */
    public void setReferrerFlag(Byte referrerFlag) {
        this.referrerFlag = referrerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_count
     *
     * @return the value of user.invite_count
     *
     * @mbg.generated
     */
    public Integer getInviteCount() {
        return inviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_count
     *
     * @param inviteCount the value for user.invite_count
     *
     * @mbg.generated
     */
    public void setInviteCount(Integer inviteCount) {
        this.inviteCount = inviteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_commission
     *
     * @return the value of user.invite_commission
     *
     * @mbg.generated
     */
    public BigDecimal getInviteCommission() {
        return inviteCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_commission
     *
     * @param inviteCommission the value for user.invite_commission
     *
     * @mbg.generated
     */
    public void setInviteCommission(BigDecimal inviteCommission) {
        this.inviteCommission = inviteCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sum_order_amount
     *
     * @return the value of user.sum_order_amount
     *
     * @mbg.generated
     */
    public BigDecimal getSumOrderAmount() {
        return sumOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sum_order_amount
     *
     * @param sumOrderAmount the value for user.sum_order_amount
     *
     * @mbg.generated
     */
    public void setSumOrderAmount(BigDecimal sumOrderAmount) {
        this.sumOrderAmount = sumOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sum_order_count
     *
     * @return the value of user.sum_order_count
     *
     * @mbg.generated
     */
    public Integer getSumOrderCount() {
        return sumOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sum_order_count
     *
     * @param sumOrderCount the value for user.sum_order_count
     *
     * @mbg.generated
     */
    public void setSumOrderCount(Integer sumOrderCount) {
        this.sumOrderCount = sumOrderCount;
    }
}
